### Send POST request with json body
POST http://localhost:1448/api/authentication/register
Content-Type: application/json

{
  "userName": "testUser2",
  "email": "testuser2@demo.com",
  "password": "StrongPassword@1"
}


### Send POST request with json body
POST http://localhost:1448/api/authentication/login
Content-Type: application/json

{
  "userName": "testUser2",
  "password": "StrongPassword@1"
}

###  

GET http://localhost:1448/api/authentication/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3RVc2VyMiIsImp0aSI6IjJmM2I4NjM4LTE0M2QtNDQ0MS05Y2JhLTAyODMyZWRmODIyYiIsIklkIjoiOGNmN2UwMDktY2U2ZC00NDNhLTk4ZmItZWUxZGMxNjU4YTdmIiwibmJmIjoxNjA2MjAwNTg2LCJleHAiOjE2MDYyMTEzODYsImlhdCI6MTYwNjIwMDU4Nn0.1Sz0PLGMBce3_7-IMlHyewZ9Y7glfsbFRVGdchenrT8

###  

GET http://localhost:1448/weatherforecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3RVc2VyMiIsImp0aSI6IjYzZjIyZTNiLWRkNTQtNDVjYi04MDU1LTZiZTQ1MjE3NzcxOCIsIklkIjoiOGNmN2UwMDktY2U2ZC00NDNhLTk4ZmItZWUxZGMxNjU4YTdmIiwibmJmIjoxNjA2MTk3NTc5LCJleHAiOjE2MDYyMDgzNzksImlhdCI6MTYwNjE5NzU3OX0.QFBwuLQ8_7i1sQ7Egha8R6oW3iA4N9Vtbl7q17ojxnE