### Send POST request with json body
POST http://localhost:1414/iapi/authentication/register
Content-Type: application/json

{
  "userName": "Dan",
  "email": "Dan@demo.com",
  "password": "StrongPassword@1"
}


### Send POST request with json body
POST http://localhost:1414/api/authentication/login
Content-Type: application/json
Authorization: Basic ZGV2QG1hZGVieWVkZW4uY29tOkVkZW5MYWJzMjAxOCE=

###  

GET http://localhost:1414/api/authentication/verifying
Authorization: : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRldkBtYWRlYnllZGVuLmNvbSIsImp0aSI6IjE1ZmFkNjFjLWVkMzItNGJlYS1iN2ViLTJkZGQ2OTRkMDliNCIsIklkIjoiMGNlMzZiODctY2EyMC00Yjk5LTlhZDEtN2U4NDM1NzkyMjEzIiwiUm9sZSI6IkFkbWluIiwibmJmIjoxNjA2OTk4NDUxLCJleHAiOjE2MDcwMDkyNTEsImlhdCI6MTYwNjk5ODQ1MX0.TAMZLnGrHvssmewAvmcUkmB_MhIOo8t4oH96TpynQoI 

###  

GET http://localhost:1414/weatherforecast
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRldkBtYWRlYnllZGVuLmNvbSIsImp0aSI6IjUzZTJmNzgxLTBmNmMtNDFjNS05MzdiLTMwMzI3MTRiZmZhOSIsIklkIjoiMGNlMzZiODctY2EyMC00Yjk5LTlhZDEtN2U4NDM1NzkyMjEzIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNjA2OTk4NjU0LCJleHAiOjE2MDcwMDk0NTQsImlhdCI6MTYwNjk5ODY1NH0.1EYCVyhu-qPPzk2GU5De3ATo1vK2QnxpkYGSMGJeTXo 

### Health End Point 

GET http://localhost:1414/actuator/health
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRldkBtYWRlYnllZGVuLmNvbSIsImp0aSI6IjUzZTJmNzgxLTBmNmMtNDFjNS05MzdiLTMwMzI3MTRiZmZhOSIsIklkIjoiMGNlMzZiODctY2EyMC00Yjk5LTlhZDEtN2U4NDM1NzkyMjEzIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNjA2OTk4NjU0LCJleHAiOjE2MDcwMDk0NTQsImlhdCI6MTYwNjk5ODY1NH0.1EYCVyhu-qPPzk2GU5De3ATo1vK2QnxpkYGSMGJeTXo

